
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqstezhjggxjuskktlaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhxc3RlemhqZ2d4anVza2t0bGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjM4MjcsImV4cCI6MjA2MDQ5OTgyN30.LasSEUf39LgRTZnMFiW4mRJNlvRUS7QQvNUc_8dgt9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Enable realtime for all tables for better data sync
const setupRealtimeSubscription = async () => {
  try {
    // Enable realtime on required tables
    await supabase.channel('public:blood_requests').subscribe();
    await supabase.channel('public:donors').subscribe();
    await supabase.channel('public:hospitals').subscribe();
    console.log("Realtime subscriptions established for all tables");
  } catch (error) {
    console.error("Error setting up realtime subscriptions:", error);
  }
};

// Call this function when the app initializes
setupRealtimeSubscription();
